image:
  repository: maxmorhardt/topfilms-primary-ui
  tag: '1.0.0'
  pullPolicy: Always
  replicas: 1
  revisionHistoryLimit: 2
  env: {}
  readinessProbe:
    path: /auth/login
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
  livenessProbe:
    path: /auth/login
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: topfilms.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: topfilms.io-tls
      hosts:
        - topfilms.io

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 80
  
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
